// <auto-generated />
using System;
using BusBookingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusBookingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019112824_AddRoleToRegister")]
    partial class AddRoleToRegister
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusBookingAPI.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BusBookingAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BusBookingAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QRToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "SeatNumber");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BusBookingAPI.Models.CheckinLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CheckinPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("StaffId");

                    b.ToTable("CheckinLogs");
                });

            modelBuilder.Entity("BusBookingAPI.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Departure", "Destination");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hà Nội",
                            Destination = "Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hà Nội",
                            Destination = "Đà Nẵng"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hà Nội",
                            Destination = "Hải Phòng"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hồ Chí Minh",
                            Destination = "Đà Lạt"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hồ Chí Minh",
                            Destination = "Cần Thơ"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Đà Nẵng",
                            Destination = "Huế"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departure = "Hà Nội",
                            Destination = "Nghệ An"
                        });
                });

            modelBuilder.Entity("BusBookingAPI.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 8,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 9,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 10,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 11,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 12,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 13,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 14,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 15,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 16,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 17,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 18,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 19,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 20,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 21,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 22,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 23,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 24,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 25,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 26,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 27,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 28,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 29,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 30,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 31,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 32,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 33,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 34,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 35,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 36,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 37,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 1
                        },
                        new
                        {
                            Id = 38,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 1
                        },
                        new
                        {
                            Id = 39,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 1
                        },
                        new
                        {
                            Id = 40,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 1
                        },
                        new
                        {
                            Id = 41,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 42,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 43,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 44,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 45,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 46,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 47,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 48,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 49,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 50,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 51,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 52,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 53,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 54,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 55,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 56,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 57,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 58,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 59,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 60,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 61,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 62,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 63,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 64,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 65,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 66,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 67,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 68,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 69,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 70,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 71,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 72,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 73,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 74,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 75,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 76,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 77,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 2
                        },
                        new
                        {
                            Id = 78,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 2
                        },
                        new
                        {
                            Id = 79,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 2
                        },
                        new
                        {
                            Id = 80,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 2
                        },
                        new
                        {
                            Id = 81,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 82,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 83,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 84,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 85,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 86,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 87,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 88,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 89,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 90,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 91,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 92,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 93,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 94,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 95,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 96,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 97,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 98,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 99,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 100,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 101,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 102,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 103,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 104,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 105,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 106,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 107,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 108,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 109,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 110,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 111,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 112,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 113,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 114,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 115,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 116,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 117,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 3
                        },
                        new
                        {
                            Id = 118,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 3
                        },
                        new
                        {
                            Id = 119,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 3
                        },
                        new
                        {
                            Id = 120,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 3
                        },
                        new
                        {
                            Id = 121,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 122,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 123,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 124,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 125,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 126,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 127,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 128,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 129,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 130,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 131,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 132,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 133,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 134,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 135,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 136,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 137,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 138,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 139,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 140,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 141,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 142,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 143,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 144,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 145,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 146,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 147,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 148,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 149,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 150,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 151,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 152,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 153,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 154,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 155,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 156,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 157,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 4
                        },
                        new
                        {
                            Id = 158,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 4
                        },
                        new
                        {
                            Id = 159,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 4
                        },
                        new
                        {
                            Id = 160,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 4
                        },
                        new
                        {
                            Id = 161,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 162,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 163,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 164,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 165,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 166,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 167,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 168,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 169,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 170,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 171,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 172,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 173,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 174,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 175,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 176,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 177,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 178,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 179,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 180,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 181,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 182,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 183,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 184,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 185,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 186,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 187,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 188,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 189,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 190,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 191,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 192,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 193,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 194,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 195,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 196,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 197,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 5
                        },
                        new
                        {
                            Id = 198,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 5
                        },
                        new
                        {
                            Id = 199,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 5
                        },
                        new
                        {
                            Id = 200,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 5
                        },
                        new
                        {
                            Id = 201,
                            IsBooked = false,
                            SeatNumber = "A1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 202,
                            IsBooked = false,
                            SeatNumber = "A2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 203,
                            IsBooked = false,
                            SeatNumber = "A3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 204,
                            IsBooked = false,
                            SeatNumber = "A4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 205,
                            IsBooked = false,
                            SeatNumber = "B1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 206,
                            IsBooked = false,
                            SeatNumber = "B2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 207,
                            IsBooked = false,
                            SeatNumber = "B3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 208,
                            IsBooked = false,
                            SeatNumber = "B4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 209,
                            IsBooked = false,
                            SeatNumber = "C1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 210,
                            IsBooked = false,
                            SeatNumber = "C2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 211,
                            IsBooked = false,
                            SeatNumber = "C3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 212,
                            IsBooked = false,
                            SeatNumber = "C4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 213,
                            IsBooked = false,
                            SeatNumber = "D1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 214,
                            IsBooked = false,
                            SeatNumber = "D2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 215,
                            IsBooked = false,
                            SeatNumber = "D3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 216,
                            IsBooked = false,
                            SeatNumber = "D4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 217,
                            IsBooked = false,
                            SeatNumber = "E1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 218,
                            IsBooked = false,
                            SeatNumber = "E2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 219,
                            IsBooked = false,
                            SeatNumber = "E3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 220,
                            IsBooked = false,
                            SeatNumber = "E4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 221,
                            IsBooked = false,
                            SeatNumber = "F1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 222,
                            IsBooked = false,
                            SeatNumber = "F2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 223,
                            IsBooked = false,
                            SeatNumber = "F3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 224,
                            IsBooked = false,
                            SeatNumber = "F4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 225,
                            IsBooked = false,
                            SeatNumber = "G1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 226,
                            IsBooked = false,
                            SeatNumber = "G2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 227,
                            IsBooked = false,
                            SeatNumber = "G3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 228,
                            IsBooked = false,
                            SeatNumber = "G4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 229,
                            IsBooked = false,
                            SeatNumber = "H1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 230,
                            IsBooked = false,
                            SeatNumber = "H2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 231,
                            IsBooked = false,
                            SeatNumber = "H3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 232,
                            IsBooked = false,
                            SeatNumber = "H4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 233,
                            IsBooked = false,
                            SeatNumber = "I1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 234,
                            IsBooked = false,
                            SeatNumber = "I2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 235,
                            IsBooked = false,
                            SeatNumber = "I3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 236,
                            IsBooked = false,
                            SeatNumber = "I4",
                            TripId = 6
                        },
                        new
                        {
                            Id = 237,
                            IsBooked = false,
                            SeatNumber = "J1",
                            TripId = 6
                        },
                        new
                        {
                            Id = 238,
                            IsBooked = false,
                            SeatNumber = "J2",
                            TripId = 6
                        },
                        new
                        {
                            Id = 239,
                            IsBooked = false,
                            SeatNumber = "J3",
                            TripId = 6
                        },
                        new
                        {
                            Id = 240,
                            IsBooked = false,
                            SeatNumber = "J4",
                            TripId = 6
                        });
                });

            modelBuilder.Entity("BusBookingAPI.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StartTime");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusName = "Xe Khách Phương Trang",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 1,
                            StartTime = new DateTime(2024, 1, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 2,
                            BusName = "Xe Khách Hoàng Long",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 1,
                            StartTime = new DateTime(2024, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 3,
                            BusName = "Xe Khách Mai Linh",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 1,
                            StartTime = new DateTime(2024, 1, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 4,
                            BusName = "Xe Khách Phương Trang",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 2,
                            StartTime = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 5,
                            BusName = "Xe Khách Hoàng Long",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 2,
                            StartTime = new DateTime(2024, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 6,
                            BusName = "Xe Khách Mai Linh",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = 3,
                            StartTime = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusBookingAPI.Models.AuditLog", b =>
                {
                    b.HasOne("BusBookingAPI.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusBookingAPI.Models.Booking", b =>
                {
                    b.HasOne("BusBookingAPI.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusBookingAPI.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusBookingAPI.Models.CheckinLog", b =>
                {
                    b.HasOne("BusBookingAPI.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusBookingAPI.Data.ApplicationUser", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BusBookingAPI.Models.Seat", b =>
                {
                    b.HasOne("BusBookingAPI.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BusBookingAPI.Models.Trip", b =>
                {
                    b.HasOne("BusBookingAPI.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusBookingAPI.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusBookingAPI.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusBookingAPI.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusBookingAPI.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
